# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:\\Users\\fakba\\.gradle\\jdks\\eclipse_adoptium-21-amd64-windows.2

# Mod Properties
mod_id=betterdisenchanter
mod_name=Better Disenchanter
mod_license=MIT
mod_version=1.1.0
mod_group_id=com.betterdisenchanter
mod_authors=Antigravity

# Minecraft & NeoForge
minecraft_version=1.21.1
neo_version=21.1.186
